export const products = [
	{
		id: 'pizza-1',
		category: 'Пицца',
		filter: 'New',
		image: '../../public/products/pizza/pizza.png',
		name: 'Чикен Сладкий Чили',
		description: 'Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный...',
		price: 389,
	},
	{
		id: 'pizza-2',
		category: 'Пицца',
		filter: 'Хит',
		image: '../../public/products/pizza/pizza (1).png',
		name: 'EASY PEASY огуречный расколбас',
		description: 'Курица, Лук, Перец Халапеньо...',
		price: 549,
	},
	{
		id: 'pizza-3',
		category: 'Пицца',
		filter: '',
		image: '../../public/products/pizza/pizza (2).png',
		name: 'EASY PEASY чикен а-ля хрен',
		description: 'Курица, Лук, Соус Карбонара,...',
		price: 249,
	},
	{
		id: 'pizza-4',
		category: 'Пицца',
		filter: '',
		image: '../../public/products/pizza/pizza (3).png',
		name: '4 сезона',
		description: 'Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...',
		price: 630,
	},
	{
		id: 'pizza-5',
		category: 'Пицца',
		filter: '',
		image: '../../public/products/pizza/pizza (4).png',
		name: '4 сезона',
		description: 'Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...',
		price: 630,
	},
	{
		id: 'pizza-6',
		category: 'Пицца',
		filter: 'Хит',
		image: '../../public/products/pizza/pizza (5).png',
		name: 'EASY PEASY чикен а-ля хрен',
		description: 'Курица, Лук, Соус Карбонара,...',
		price: 249,
	},
	{
		id: 'pizza-7',
		category: 'Пицца',
		filter: '',
		image: '../../public/products/pizza/pizza (6).png',
		name: 'Чикен Сладкий Чили',
		description: 'Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный...',
		price: 399,
	},
	{
		id: 'pizza-8',
		category: 'Пицца',
		filter: '',
		image: '../../public/products/pizza/pizza (7).png',
		name: 'EASY PEASY огуречный расколбас',
		description: 'Курица, Лук, Перец Халапеньо...',
		price: 549,
	},
	{
		id: 'combo-1',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (8).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр, креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
		discount: 22,
	},
	{
		id: 'combo-2',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (9).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
		discount: 18,
	},
	{
		id: 'combo-3',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (10).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
		discount: 10,
	},
	{
		id: 'combo-4',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (11).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
		discount: 15,
	},
	{
		id: 'combo-5',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (12).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
		discount: 18,
	},
	{
		id: 'combo-6',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (8).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
		discount: 22,
	},
	{
		id: 'combo-7',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (11).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
		discount: 15,
	},
	{
		id: 'combo-8',
		category: 'Комбо',
		fillter: '',
		image: '../../public/products/kombo/kombo (10).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
		discount: 10,
	},
	{
		id: 'sushi-1',
		category: 'Суши',
		filter: 'New',
		image: '../../public/products/sushi/sushi (1).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
	},
	{
		id: 'sushi-2',
		category: 'Суши',
		filter: 'Xit',
		image: '../../public/products/sushi/sushi (2).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
	},
	{
		id: 'sushi-3',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (3).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
	},
	{
		id: 'sushi-4',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (4).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
	},
	{
		id: 'sushi-5',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (4).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
	},
	{
		id: 'sushi-6',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (3).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
	},
	{
		id: 'sushi-7',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (1).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
	},
	{
		id: 'sushi-8',
		category: 'Суши',
		filter: '',
		image: '../../public/products/sushi/sushi (2).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
	},
	{
		id: 'Snacks-1',
		category: 'Закуски',
		filter: 'New',
		image: '../../public/products/snacks/snacks (1).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
	},
	{
		id: 'Snacks-2',
		category: 'Закуски',
		filter: 'Xit',
		image: '../../public/products/snacks/snacks (2).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
	},
	{
		id: 'Snacks-3',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/snacks/snacks (3).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
	},
	{
		id: 'Snacks-4',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/snacks/snacks (4).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
	},
	{
		id: 'Snacks-5',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/snacks/snacks (4).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 525,
	},
	{
		id: 'Snacks-6',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/snacks/snacks (3).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
	},
	{
		id: 'Snacks-7',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/pizza/pizza (6).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
	},
	{
		id: 'Snacks-8',
		category: 'Закуски',
		filter: '',
		image: '../../public/products/pizza/pizza (6).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
	},
	{
		id: 'desert-1',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (6).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		filter: 'NEW',
		price: 475,
	},
	{
		id: 'desert-2',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (1).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		filter: 'ХИТ',
		price: 395,
	},
	{
		id: 'desert-3',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (2).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		filter: '',
		price: 425,
	},
	{
		id: 'desert-4',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (3).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		filter: '',
		price: 525,
	},
	{
		id: 'desert-5',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (3).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		filter: '',
		price: 525,
	},
	{
		id: 'desert-6',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (4).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		filter: '',
		price: 395,
	},
	{
		id: 'desert-7',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (5).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		filter: '',
		price: 475,
	},
	{
		id: 'desert-8',
		category: 'Десерты',
		image: '../../public/products/dessert/dessert (2).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		filter: '',
		price: 425,
	},
	{
		id: 'drink-1',
		category: 'Напитки',
		filter: 'New',
		image: '../../public/products/drinks/drinks (1).png',
		name: 'Филадельфия кранч',
		description:
			'Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...',
		price: 475,
	},
	{
		id: 'drink-2',
		category: 'Напитки',
		filter: 'Хит',
		image: '../../public/products/drinks/drinks (2).png',
		name: 'Филадельфия крем-брюле',
		description:
			'Сливочный сыр, семга татаки с тростниковым сахаром,у...',
		price: 395,
	},
	{
		id: 'drink-3',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (3).png',
		name: 'Супер Филадельфия',
		description: 'Действительно много семги, сливочный сыр, огурец, рис, н...',
		price: 425,
	},
	{
		id: 'drink-4',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (4).png',
		name: 'Тигр мама',
		description: 'Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...',
		price: 425,
	},
	{
		id: 'drink-5',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (5).png',
		name: 'Супер Филадельфия',
		description: '',
		price: 425,
	},
	{
		id: 'drink-6',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (6).png',
		name: 'Тигр мама',
		description: '',
		price: 525,
	},
	{
		id: 'drink-7',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (1).png',
		name: 'Супер Филадельфия',
		description: '',
		price: 425,
	},
	{
		id: 'drink-8',
		category: 'Напитки',
		filter: '',
		image: '../../public/products/drinks/drinks (2).png',
		name: 'Тигр мама',
		description: '',
		price: 525,
	},
	{
		id: 'sauce-1',
		category: 'Соусы',
		filter: 'NEW',
		image: '../../public/products/sous/sous (1).png',
		name: 'Филадельфия кранч',
		description: '',
		price: 475,
	},
	{
		id: 'sauce-2',
		category: 'Соусы',
		filter: 'ХИТ',
		image: '../../public/products/sous/sous (2).png',
		name: 'Филадельфия крем-брюле',
		description: '',
		price: 395,
	},
	{
		id: 'sauce-3',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (4).png',
		name: 'Супер Филадельфия',
		description: '',
		price: 425,
	},
	{
		id: 'sauce-4',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (3).png',
		name: 'Тигр мама',
		description: '',
		price: 525,
	},
	{
		id: 'sauce-5',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (2).png',
		name: 'Филадельфия крем-брюле',
		description: '',
		price: 395,
	},
	{
		id: 'sauce-6',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (3).png',
		name: 'Тигр мама',
		description: '',
		price: 525,
	},
	{
		id: 'sauce-7',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (4).png',
		name: 'Супер Филадельфия',
		description: '',
		price: 425,
	},
	{
		id: 'sauce-8',
		category: 'Соусы',
		filter: '',
		image: '../../public/products/sous/sous (1).png',
		name: 'Филадельфия кранч',
		description: '',
		price: 475,
	},
]
